src/nodejs/analytics/analytics.cpp, src/nodejs/analytics/analytics.h, src/nodejs/analytics/run.js, src/nodejs/la/la_nodejs.cpp, src/nodejs/la/la_nodejs.h, src/nodejs/la/run.js, src/nodejs/nodeutil.cpp, src/nodejs/nodeutil.h
Summary of changes:
- ported tokenizer from the old QM JS API to analytics addon;
- added indexed property handlers to vector and sparse matrix objects from the LA addon;
- fixed bug in `JsDeclareSetIndexedProperty(FunctionGetter, FunctionSetter)` macro in `nodeutil.h`.
=> Ported tokenizer

binding.gyp
-Wall is set by default in common.gypi that comes with node. -frtti and -fexceptions was duplicated.  we do not need to specify -g: it is used by default for debug configuration and ommited for realese for smaller binary size (used for publish). this is set in common.gypi
=> cleaned g++ flags

src/qminer/qminer_aggr.h, src/qminer/qminer_core.cpp, test/nodejs/streamaggr2.js
Added new exception-based asserts when accessing and adding aggregates. So far the code died if it tried to access non-existing aggregate.
=> New asserts for aggregate

src/glib/Makefile, src/glib/Makefile.config, src/glib/base/bd.h, test/cpp/Makefile, test/cpp/Makefile.debian, test/cpp/test-tpt.cpp, test/cpp/tests.vcxproj
* A class `Child` is declared with one of the `ClassTPE*()` macros and inherits from a `Parent` class.
* Instances of `Child` are created exclusively within `TPt<Child>` (aka `PChild`) shared pointers using `Child::New()` (as is common in GLib-style code).
We now want to create some generic function that accepts instances of any `TPt<Parent>` (aka `PParent`) object even if it's really an instance of a derived class.
Currently, classes declared with the `ClassTP*()` macros must always be shared with `TPt` pointers that share the same type.  Eg: if there is a Child class that inherits from a Parent class, any individual Child instance must always be owned/managed by a set of shared pointers of type `TPt<Child>` (aka `PChild`) *or* `TPt<Parent>` (aka `PParent), but not a combination of the …
=> Allow an object that's an instance of a ClassTPE*()-defined class to be managed by both parent and child class shared pointers

src/qminer/qminer_storage.cpp
Code for new `int16` and `int64` types was copy-pasted in one place and not fixed.
=> Minor fix of code

.gitignore, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h, test/nodejs/jointest.js
Added support for changing location of field-join fields (rec-id and frequency). So far they were always in memory, now they can be stored in cache using `storage_location` property of join. Possible values are `memory` and `cache` - the same as flag `store` for ordinary fields.
Also exposed some field-join related methods from `TRec` to `TStore`.
=> Location of field-join fields

src/glib/base/ds.h, src/glib/base/hash.h, src/nodejs/analytics/analytics.cpp, src/qminer/qminer_aggr.cpp
New feature:
- Added move constructor and assignment operator to `TKeyDat`
- Added move assignment operator to `THashKeyDat`
Bug fixes:
- Removed clang compile warnings for MDS and TTimeSpan.
=> Move constructors

src/nodejs/la/la_structures_nodejs.cpp, src/nodejs/la/la_structures_nodejs.h, src/qminer/qminer_aggr.h, test/nodejs/linearalgebra.js
Features:
- Added `submat` function to `SparseMatrix` that gets `IntVector` of column ids and returns sparse matrix constructed from selected columns.
- Added `clear` function to `SparseMatrix` that clears its content and sets rows to -1.
Bug fix:
- Removed unused member `Count` from `TTimeSpan`
=> Added submat and clear functions to SparseMatrix

src/glib/base/blobbs.cpp, src/glib/base/blobbs.h
Increased blob base segment from `uchar` to `uint16`. Now `TMBlobBs` can store **128TB** of stuff.
=> `TBlobPt::Seg` changed from `uchar` to `int16`

src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h
`TStoreImpl` can tell integer ID for codebook strings. `TFieldDesc` can tell if field is encoded using codebook.
=> Faster codebook string fields access

src/nodejs/qm/qm_nodejs_streamaggr.cpp, src/nodejs/qm/qm_nodejs_streamaggr.h, src/qminer/qminer_aggr.cpp, src/qminer/qminer_aggr.h, src/qminer/qminer_aggr.hpp, src/qminer/qminer_core.h
This was needed in order to avoid diamond patterns in multiple inheritances.
=> Changed TStreamAggrOut interfaces to be flat

src/glib/base/json.cpp
. Calling DelObjKey on key that is first in KeyValH makes following serialization invalid. ObjKeyN starts with 1 which makes invalid json object. Relevant change is in TJsonVal::GetChAFromVal()
=> important bug fix related to Json serialization

src/glib/base/linalg.hpp, src/glib/mine/clustering.h, src/nodejs/analytics/analytics.cpp, test/nodejs/Kmeanstest.js
Issue #449: Not all methods used for KMeans.fit were implemented when using distanceType: "Cos". Added unit tests for the fit and predict methods in the case of distanceType: "Cos".
=> KMeans.fit for distanceType: "Cos" Fix and Unit tests 

src/nodejs/analytics/analytics.cpp, src/nodejs/analytics/analytics.h, src/nodejs/fs/fs_nodejs.h, src/nodejs/ht/IntFltDocData.js, src/nodejs/ht/IntIntDocData.js, src/nodejs/ht/IntStrDocData.js, src/nodejs/ht/StrFltDocData.js, src/nodejs/ht/StrIntDocData.js, src/nodejs/ht/StrStrDocData.js, src/nodejs/ht/htDocHead.js, src/nodejs/ht/ht_nodejs.h, src/nodejs/la/BoolVectorDocData.js, src/nodejs/la/IntVectorDocData.js, src/nodejs/la/StrVectorDocData.js, src/nodejs/la/VectorDocData.js, src/nodejs/la/la_nodejs.h, src/nodejs/la/la_structures_nodejs.h, src/nodejs/la/la_vector_nodejs.h, src/nodejs/qm/qm_nodejs.h, src/nodejs/qm/qm_nodejs_streamaggr.h, src/nodejs/scripts/analytics.js, src/nodejs/scripts/fs.js, src/nodejs/scripts/la.js, src/nodejs/scripts/qm.js, src/nodejs/scripts/statistics.js, src/nodejs/statistics/stat_nodejs.h, tools/genNodeDoc.bat, tools/genNodeDoc.sh
Added missing types, descriptions, links and methods. The parameters now have a more detailed descriptions (if it was possible). Tried to reduce the number of clicks to get to a specific information, e.g. if it was possible and reasonable to put the possible options in the descriptions, it was done.  
Tokenizer now uses a default constructor value. An example to show the change:
```Javascript
var analytics = require('qminer').analytics;
// default constructor uses type: "unicode"
var defaultTokenizer = new analytics.Tokenizer();
// if given an empty object, constructor uses type: "unicode"
var emptyTokenizer = new analytics.Tokenizer({});
// if given an object with the "type" key, uses that type
var customTokenizer = new analytics.Tokenizer({ type: 'html' });
```
=> Documentation update and tokenizer default value at constructor

src/nodejs/analytics/analytics.cpp, tools/changeDocHeader.js, tools/genNodeDoc.bat, tools/genNodeDoc.sh
Documentation now has a custom `QMiner JavaScript API v<% require('qminer').version %>` header, which marks for which version the documentation is valid.
Made the code consistent in the constructor. Basically code cleanup.
=> Documentation Header and Tokenizer Fix

src/glib/base/json.h, src/glib/mine/kerneldensity.cpp, src/nodejs/qm/qm_nodejs.cpp, src/nodejs/qm/qm_nodejs_store.cpp, src/qminer/qminer_aggr.hpp
previous fix of uint64 cast of double (undefined) to (unsigned)(int64) was wrong: (unsigned long long)(int64) works as it should
=> bugfix TJsonVal::GetUInt64

src/qminer/qminer_aggr.cpp, src/qminer/qminer_ftr.cpp
Sparse vectors were not generated correctly because the SpV was not initialized and contained old values.
=> TFtrSp bug fix.

.travis.yml, README.md, appveyor.yml, test/nodejs/streamaggr.js
Fixed unit tests so that they adhere to the standard [1].
[1] http://www.ecma-international.org/ecma-262/6.0/#sec-date-time-string-format
*If the time zone offset is absent, the date-time is interpreted as a local time.*
=> nodejs 8 upgrade

src/nodejs/qm/qm_nodejs.cpp, test/nodejs/recordset.js
For stores that allow null fields in their schema, calling getVector on a rec set crashed qminer because it was trying to retrieve null elements. Now we first check through RecId and FieldId if the element is null and add it otherwise.
=> Bugfix for TNodeJsRecSet::getVector and corresponding unit tests.

src/glib/base/gix.h, src/glib/base/gix.hpp, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_core.hpp, test/nodejs/search.js
Tiny joins now counted as having frequency 1 when doing joins with record sets
=> Fixed #550: no frequency for tiny joins

src/glib/base/url.cpp, src/glib/base/url.h
to avoid breaking changes by changing the existing method TUrl::DecodeUrlStr I've added a new method TUrl::UnquoteUrlStr. The method is an equivalent to Python's urllib.parse.unquote
=> added TUrl::UnquoteUrlStr

.travis.yml, appveyor.yml, package.json, src/glib/base/linalg.cpp, src/glib/base/xmath.h, test/nodejs/statistics.js
Before, QMiner crashed if 0x0 sized matrix was passed to std or zscore function.
=> Bug fix in standard deviation function.

src/glib/base/unicode.h, src/glib/mine/clustering.hpp
[unicode.h] One version of TUniCodec::EncodeUtf8Str forgot to add a null terminator before creating a TStr instance, resulting in strings with garbage at the end (and potentially a crash).
[clustering.hpp] In MSVC, methods of TDpMeans<TFltVV> in clustering.hpp don't see members inherited from TAbsKMeans<TFltVV> unless accessed through the 'this' pointer.
=> Small fixes in unicode.h and clustering.cpp
