src/nodejs/scripts/eventRegistry.js, test/nodejs/eventRegistry.js
Added EventRegistry api module:
- suggesting concepts
- retrieving events, articles and recent activity
- searching events
=> eventRegistry.js API module added

src/nodejs/scripts/analytics.js
KMeans algorithm can now accept ¸fitStart parameter that explicitly defines starting centroids. This object should look the same as the result of the getModel() method.
=> KMeans algorithm - new parameter fitStart

test/nodejs/Svctest.js, test/nodejs/Svrtest.js, test/nodejs/merger.js, test/nodejs/movies.js, test/nodejs/onevsall.js, test/nodejs/primaryField.js, test/nodejs/store.js, test/nodejs/streamaggr.js, test/nodejs/test.sh
this is controlled using mocha --timeout paramter
=> manual timeouts in unit tests removed

.travis.yml, appveyor.yml
fixed behaviour on pull request.
=> [publish binary]

src/nodejs/qm/qm_nodejs.cpp, src/nodejs/qm/qm_nodejs.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, test/nodejs/streamaggr.js
store.triggerOnAddCallbacks(),
store.triggerOnAddCallbacks(rec),
store.triggerOnAddCallbacks(recId)
store.push(rec, false) inserts without calling onAdd updates
=> added manual control over onAdd stream aggregate callbacks.

src/glib/mine/signalproc.cpp, src/glib/mine/signalproc.h, src/nodejs/qm/qm_nodejs_streamaggr.cpp, src/nodejs/qm/qm_nodejs_streamaggr.h, test/nodejs/streamaggr.js
-  TNodeJsFuncStreamAggr supports the IsInit method of the StreamAggr …interface prived by init function
- unit test for init
- TOnlineHistogram supports additional init logic by specifying minimum count (if we have less than the given min, init is false)
=> stream aggregate init logic

src/qminer/qminer_aggr.h, test/nodejs/streamaggr2.js
- feature space winbuf save/load fix
- feature space winbuf save/load test
=> feature space winbuf fix

src/nodejs/fs/fs_nodejs.cpp, src/nodejs/fs/fs_nodejs.h, src/nodejs/scripts/fs.js
- writeJson and readJson do not parse and stringity in C++ but instea…d use JSON.stringify and JSON.parse
- added readString to FIn that complements FOut.writeBinary
=> fs: reading and writing JSON

.travis.yml, appveyor.yml, binding.gyp, src/glib/mine/svm.h, test/nodejs/streamaggr.js
-SVR debug test fix
-tdigest test currently skipped
=> debug builds are now tested

src/nodejs/analytics/analytics.cpp, test/nodejs/MDStest.js
Added the default case in the switch function.
Wrote some additional tests for MDS.
=> Debugged the MDS class.

src/qminer/qminer_core.h
```
virtual void OnStep() { }
virtual void OnTime(const uint64& TmMsec) { OnStep(); }
virtual void OnAddRec(const TRec& Rec) { OnStep(); }
```
=> OnStep, OnTime, OnAddRec default behaviour

src/qminer/qminer_storage.cpp, test/nodejs/store.js
Bug fix:
- Primary keys could be set to existing values belonging to other records. Now we throw exception in such cases. Added corresponding tests.
=> Bug fix: changing primary field values

src/glib/base/blobbs.cpp, src/glib/base/blobbs.h, src/glib/base/cache.h, src/glib/base/lx.h, src/glib/base/pgblob.cpp, src/qminer/qminer_aggr.cpp, src/qminer/qminer_aggr.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_ftr.cpp, src/qminer/qminer_ftr.h, src/qminer/qminer_srv.cpp, src/qminer/qminer_srv.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h, src/third_party/Snap/snap-core/centr.cpp
New features:
- Stores from same `TBase` share same `PBlobBs`. Speed improvements for 1000 empty stores:
- create: 0.5s vs 21s
- save: 0.6s vs 5s
- load: 0.06s vs 4s
- Removed unused flags from blob pointer, freeing 37.5% space per `TBlobPt`
Bug fixes:
- fixed clang warnings
- changed tabs to four spaces on qminer source files
=> BREAKING: stores share same BlobBs

src/glib/mine/ftrgen.cpp, src/glib/mine/ftrgen.h, src/qminer/qminer_ftr.cpp
It sets value of all non-zero features in feature vector to 1
=> Added binary option to multinomial feature extractor

src/glib/base/StackWalker.h, src/glib/base/http.cpp, src/glib/base/http.h, src/glib/base/xfl.cpp, src/glib/net/sappsrv.cpp, src/third_party/libuv/libuv.vcxproj
- web requests add a X-Response-Time containing number of milliseconds used to complete the request
=> minor updates

src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp
- speedup of recset sortbyfield
- added GetFieldNmByte
=> speedup to TRecSet::SortByField + added TStore::GetFieldNmByte

src/qminer/qminer_storage.cpp
=> bug fix for LoadBase

src/glib/base/ds.hpp, src/glib/base/dt.cpp, src/glib/base/dt.h, src/glib/base/hash.h, src/glib/base/pgblob.cpp, src/glib/base/pgblob.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h
a larger pull request. mostly about fixes needed for making TStorePbBlob work properly like TStoreImpl. Also some changes in glib that it would be welcomed if somebody can validate
=> bug fixes for TStorePbBlob + various updates

src/glib/base/pgblob.cpp, src/glib/base/pgblob.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h
the last commit contains a critical bug fix:  setting a nullable field with variable length to some value did not put the null flag to false
=> smaller updates + critical bug fix

src/nodejs/qm/qm_nodejs_streamaggr.cpp, src/nodejs/qm/qm_nodejs_streamaggr.h, test/nodejs/streamaggr.js
Very useful to have when working with JS implemented stream aggregates :)
=> JS stream aggregate: fixes `this` + included stacktraces in exceptions

src/nodejs/qm/qm_nodejs.cpp
Doesn't check if the db folder is empty, but only that StoreList.json doesn't exist.
=> minor fix for create base

binding.gyp, src/nodejs/analytics/analytics.cpp, src/nodejs/analytics/analytics.h, src/nodejs/modinit.cpp, src/nodejs/nodeutil.cpp, src/nodejs/nodeutil.h, src/nodejs/nodeutil.hpp, src/snap_ext/graphprocess.cpp, src/snap_ext/graphprocess.h, test/nodejs/graphCascades.js
- added graph cascade model (models timestamps of full directed acyclic graph sweeps)
- C++ exceptions stack-traces in nodejs
=> graph cascades model

src/glib/mine/signalproc.cpp, src/glib/mine/signalproc.h, src/nodejs/qm/qm_nodejs_streamaggr.cpp, src/nodejs/qm/qm_nodejs_streamaggr.h, src/qminer/qminer_aggr.cpp, src/qminer/qminer_aggr.h, src/qminer/qminer_core.cpp, test/nodejs/streamaggr.js
The resampler computes aggregates over consecutive equally sized intervals. It implements summing, averaging, max and min.
=> aggregating resampler

src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, test/nodejs/streamaggr.js
- Added `saveState` and `loadState` for `TStreamAggrSet`
- `saveJson()` returns names (IDs) of aggregates in a set
=> Save & Load method for aggregate 'set'

src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h
First step towards memory-only base
=> Store that does not store any records

.gitignore, src/glib/base/bd.h, src/glib/base/cache.h, src/glib/base/ds.h, src/glib/base/ds.hpp, src/glib/base/dt.h, src/glib/base/gix.h, src/glib/base/hash.h, src/glib/base/json.cpp, src/glib/base/json.h, src/glib/base/tm.h, src/glib/mine/anomaly.cpp, src/glib/mine/anomaly.h, src/glib/mine/bowbs.h, src/nodejs/qm/qm_nodejs.h, src/qminer/qminer_aggr.cpp, src/qminer/qminer_aggr.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_ftr.cpp, test/cpp/Makefile, test/cpp/install_linux.sh, test/cpp/test-sizeof.cpp, test/cpp/test-traits.cpp, test/nodejs/featurespace.js, test/nodejs/streamaggr.js
- created common API for calculating memory usage in containers
- calculating stream aggregates memory footprint
- type trait API for detecting shallow types and containers
- optimized TVec memory footprint calculation using type traits (only for C++11)
- new API for multinomial feature extractor transformation
=> TVec, THash and stream aggregates footprint + TMultinomial transform API

src/glib/base/gix.hpp, src/qminer/qminer_core.cpp
- items are not necessarily sorted
- Def() has to be called in case some items were deleted
=> two bug fixes related to positional text indexing

src/glib/base/bd.h, src/glib/base/hash.h, src/glib/base/shash.h, src/glib/base/xmlser.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h
- added TWPt serialization as in TPt
- updated TStrHash.GetMemUsed() which used the nonavailable GetMemUsedDeep() method
- added filtering classes TRecFilterByFieldByteSet, TRecFilterByFieldUIntSet, TRecFilterByFieldUInt64Set
=> some added record filtering classes and methods

src/glib/base/bd.h, src/glib/base/gix.h, src/glib/base/gix.hpp, src/glib/base/os.cpp, src/glib/base/pgblob.cpp, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, test/nodejs/search.js
updated positional text indexing. Uses modulo 1024 instead of 256 (less false positives), stores all mentions of words in a document (before limited to 8 occurrences) and uses about 20% less space for the index.
=> Pos index optimization

test/nodejs/featurespace.js
The PR contains a unit test to check if the bow feature extractor using hashDimension returns the correct feature values for previously seen and unseen words.
=> BoW hashDimension unit test

src/glib/mine/clustering.h, src/glib/mine/clustering.hpp, src/glib/mine/nmf.h, src/glib/mine/svm.h, src/glib/mine/vizmap.cpp, src/glib/mine/vizmap.h, src/nodejs/analytics/analytics.cpp, src/nodejs/analytics/analytics.h
(PNotify -> TWPt<TNotify>) to prevent segmentation faults when node exits
=> Smart pointer notify objects changed to weak pointers (analytics)

src/glib/base/json.cpp, src/glib/base/json.h, src/nodejs/fs/fs_nodejs.cpp, src/nodejs/fs/fs_nodejs.h, src/nodejs/qm/qm_nodejs.cpp, src/nodejs/qm/qm_nodejs.h, src/nodejs/qm/qm_nodejs_store.h, src/qminer/qminer_core.cpp, src/qminer/qminer_core.h, src/qminer/qminer_storage.cpp, src/qminer/qminer_storage.h, test/nodejs/store.js
Fixed #459 : `PJsonVal` returning temporary strings given as default value by reference
Fixed #446 : Added timeout parameter to `TStore::GarbageCollect()`
Fixes #455 : Fixed documentation and example for `fs.readLines(...)`
=> Fixing issues

src/qminer/qminer_core.cpp, test/nodejs/newRecord.js
Still missing the implementation for blob though.
=> Added implementation for JSON parsing in newRecord

src/glib/net/websrv.cpp
Until now TWebSrv::OnRead tried to parse the whole request (by constructing a THttpRq instance) every time it received new data.  If the request has a long body (e.g. 10+ MB) and the data keeps coming in small increments, this leads to a O(n^2) time complexity and can easily cause timeouts or unexpectedly slow response times.
The current patch adds a timesaving check: if the data received so far includes a Content-Length header and it is clear from its value that the request body has not yet been received in its entirety, there is no point in even trying to parse it, so we don't.
=> Fix a gross inefficiency in TWebSrv when receiving a long request
